[Thu Dec 02 13:42:28.634200 2021] [wsgi:error] [pid 51861:tid 140152609326848] [remote 36.82.95.104:50319] /home/temperantia/All_TavernofSoul/TavernofSoul/Items/views.py:17: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Thu Dec 02 13:42:28.634438 2021] [wsgi:error] [pid 51861:tid 140152609326848] [remote 36.82.95.104:50319] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Thu Dec 02 13:42:28.634443 2021] [wsgi:error] [pid 51861:tid 140152609326848] [remote 36.82.95.104:50319]   import numpy as np
[Thu Dec 02 13:42:29.313004 2021] [core:error] [pid 51865:tid 140152424851200] (13)Permission denied: [client 36.82.95.104:50319] AH00035: access to /static/js/jquery.min.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/js') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:42:29.404640 2021] [core:error] [pid 51864:tid 140152416458496] (13)Permission denied: [client 36.82.95.104:50320] AH00035: access to /static/css/style.css denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/css') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:42:29.407536 2021] [core:error] [pid 51865:tid 140152416458496] (13)Permission denied: [client 36.82.95.104:50322] AH00035: access to /static/js/main.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/js') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:42:30.028444 2021] [core:error] [pid 51864:tid 140152500385536] (13)Permission denied: [client 36.82.95.104:50320] AH00035: access to /static/images/Discord-Logo-White.png denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/images') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:42:30.028803 2021] [core:error] [pid 51865:tid 140152500385536] (13)Permission denied: [client 36.82.95.104:50322] AH00035: access to /static/images/Twitter-logo-white.png denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/images') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:42:30.071915 2021] [core:error] [pid 51865:tid 140152584148736] (13)Permission denied: [client 36.82.95.104:50324] AH00035: access to /static/images/logo.png denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/images') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:42:30.442880 2021] [core:error] [pid 51864:tid 140152584148736] (13)Permission denied: [client 36.82.95.104:50321] AH00035: access to /static/js/popper.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/js') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:42:30.443082 2021] [core:error] [pid 51864:tid 140152584148736] (13)Permission denied: [client 36.82.95.104:50323] AH00035: access to /static/js/bootstrap.min.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/js') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:42:30.543446 2021] [core:error] [pid 51865:tid 140152491992832] (13)Permission denied: [client 36.82.95.104:50324] AH00035: access to /static/js/main.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/js') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:42:37.965812 2021] [core:error] [pid 51865:tid 140152483600128] (13)Permission denied: [client 36.82.95.104:50334] AH00035: access to /static/js/jquery.min.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/js') because search permissions are missing on a component of the path
[Thu Dec 02 13:44:42.110531 2021] [core:error] [pid 51865:tid 140152399673088] (13)Permission denied: [client 36.82.95.104:57186] AH00035: access to /static/js/jquery.min.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/js') because search permissions are missing on a component of the path
[Thu Dec 02 13:44:45.109108 2021] [core:error] [pid 51864:tid 140152466814720] (13)Permission denied: [client 36.82.95.104:57190] AH00035: access to /static/js/jquery.min.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/js') because search permissions are missing on a component of the path
[Thu Dec 02 13:44:47.352278 2021] [core:error] [pid 51865:tid 140152450029312] (13)Permission denied: [client 36.82.95.104:57197] AH00035: access to /static/js/jquery.min.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/js') because search permissions are missing on a component of the path
[Thu Dec 02 13:44:48.344705 2021] [core:error] [pid 51865:tid 140152433243904] (13)Permission denied: [client 36.82.95.104:57197] AH00035: access to /static/js/jquery.min.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/js') because search permissions are missing on a component of the path
[Thu Dec 02 13:44:55.670959 2021] [core:error] [pid 51864:tid 140152349316864] (13)Permission denied: [client 36.82.95.104:57204] AH00035: access to /static/css/style.css denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/css') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:44:55.760164 2021] [core:error] [pid 51865:tid 140152600934144] (13)Permission denied: [client 36.82.95.104:57209] AH00035: access to /static/js/popper.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/js') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:44:55.765094 2021] [core:error] [pid 51864:tid 140152450029312] (13)Permission denied: [client 36.82.95.104:57204] AH00035: access to /static/images/Twitter-logo-white.png denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/images') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:44:55.765545 2021] [core:error] [pid 51865:tid 140152475207424] (13)Permission denied: [client 36.82.95.104:57207] AH00035: access to /static/js/bootstrap.min.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/js') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:44:55.765817 2021] [core:error] [pid 51865:tid 140152424851200] (13)Permission denied: [client 36.82.95.104:57208] AH00035: access to /static/js/jquery.min.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/js') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:44:55.766223 2021] [core:error] [pid 51864:tid 140152366102272] (13)Permission denied: [client 36.82.95.104:57205] AH00035: access to /static/js/main.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/js') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:44:55.844831 2021] [core:error] [pid 51865:tid 140152416458496] (13)Permission denied: [client 36.82.95.104:57206] AH00035: access to /static/images/Discord-Logo-White.png denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/images') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:44:55.850750 2021] [core:error] [pid 51865:tid 140152500385536] (13)Permission denied: [client 36.82.95.104:57209] AH00035: access to /static/images/logo.png denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/images') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:44:55.871781 2021] [core:error] [pid 51864:tid 140152433243904] (13)Permission denied: [client 36.82.95.104:57205] AH00035: access to /static/js/popper.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/js') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:44:55.984194 2021] [core:error] [pid 51865:tid 140152584148736] (13)Permission denied: [client 36.82.95.104:57207] AH00035: access to /static/js/bootstrap.min.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/js') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:44:56.084032 2021] [core:error] [pid 51865:tid 140152491992832] (13)Permission denied: [client 36.82.95.104:57208] AH00035: access to /static/js/main.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/js') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:45:11.435849 2021] [core:error] [pid 51864:tid 140152424851200] (13)Permission denied: [client 36.82.95.104:57216] AH00035: access to /static/images/logo.png denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/images') because search permissions are missing on a component of the path
[Thu Dec 02 13:45:32.255617 2021] [core:error] [pid 51865:tid 140152483600128] (13)Permission denied: [client 36.82.95.104:57223] AH00035: access to /static/images/logo.png denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/images') because search permissions are missing on a component of the path
[Thu Dec 02 13:45:33.021003 2021] [core:error] [pid 51865:tid 140152609326848] (13)Permission denied: [client 36.82.95.104:57223] AH00035: access to /static/images/logo.png denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/images') because search permissions are missing on a component of the path
[Thu Dec 02 13:45:33.991214 2021] [core:error] [pid 51865:tid 140152466814720] (13)Permission denied: [client 36.82.95.104:57223] AH00035: access to /static/images/logo.png denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/images') because search permissions are missing on a component of the path
[Thu Dec 02 13:45:34.806480 2021] [core:error] [pid 51865:tid 140152441636608] (13)Permission denied: [client 36.82.95.104:57223] AH00035: access to /static/images/logo.png denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/images') because search permissions are missing on a component of the path
[Thu Dec 02 13:45:35.631180 2021] [core:error] [pid 51865:tid 140152399673088] (13)Permission denied: [client 36.82.95.104:57223] AH00035: access to /static/images/logo.png denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/images') because search permissions are missing on a component of the path
Exception ignored in: <function Local.__del__ at 0x7f77caac0c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Thu Dec 02 13:46:26.367974 2021] [core:error] [pid 52118:tid 139952826304256] (13)Permission denied: [client 36.82.95.104:57231] AH00035: access to /static/images/logo.png denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/images') because search permissions are missing on a component of the path
[Thu Dec 02 13:46:28.356115 2021] [core:error] [pid 52118:tid 139952809518848] (13)Permission denied: [client 36.82.95.104:57231] AH00035: access to /static/images/logo.png denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/images') because search permissions are missing on a component of the path
[Thu Dec 02 13:46:30.964535 2021] [core:error] [pid 52118:tid 139952901838592] (13)Permission denied: [client 36.82.95.104:57238] AH00035: access to /static/images/logo.png denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/images') because search permissions are missing on a component of the path
[Thu Dec 02 13:46:31.916403 2021] [wsgi:error] [pid 52114:tid 139953038272256] [remote 36.82.95.104:57238] /home/temperantia/All_TavernofSoul/TavernofSoul/Items/views.py:17: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Thu Dec 02 13:46:31.916478 2021] [wsgi:error] [pid 52114:tid 139953038272256] [remote 36.82.95.104:57238] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Thu Dec 02 13:46:31.916484 2021] [wsgi:error] [pid 52114:tid 139953038272256] [remote 36.82.95.104:57238]   import numpy as np
[Thu Dec 02 13:46:32.847997 2021] [core:error] [pid 52118:tid 139952792733440] (13)Permission denied: [client 36.82.95.104:57244] AH00035: access to /static/images/logo.png denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/images') because search permissions are missing on a component of the path
[Thu Dec 02 13:46:35.244185 2021] [core:error] [pid 52117:tid 139953004701440] (13)Permission denied: [client 36.82.95.104:57248] AH00035: access to /static/css/style.css denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/css') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:46:35.327371 2021] [core:error] [pid 52118:tid 139953021486848] (13)Permission denied: [client 36.82.95.104:57255] AH00035: access to /static/js/popper.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/js') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:46:35.327627 2021] [core:error] [pid 52118:tid 139953021486848] (13)Permission denied: [client 36.82.95.104:57257] AH00035: access to /static/js/bootstrap.min.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/js') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:46:35.327844 2021] [core:error] [pid 52117:tid 139953046664960] (13)Permission denied: [client 36.82.95.104:57256] AH00035: access to /static/js/jquery.min.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/js') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:46:35.332167 2021] [core:error] [pid 52117:tid 139952996308736] (13)Permission denied: [client 36.82.95.104:57254] AH00035: access to /static/js/main.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/js') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:46:35.532550 2021] [core:error] [pid 52118:tid 139952868267776] (13)Permission denied: [client 36.82.95.104:57255] AH00035: access to /static/js/popper.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/js') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:46:35.779455 2021] [core:error] [pid 52118:tid 139952834696960] (13)Permission denied: [client 36.82.95.104:57257] AH00035: access to /static/js/bootstrap.min.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/js') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:46:35.927616 2021] [core:error] [pid 52117:tid 139952918624000] (13)Permission denied: [client 36.82.95.104:57254] AH00035: access to /static/images/Discord-Logo-White.png denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/images') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:46:35.927812 2021] [core:error] [pid 52117:tid 139952918624000] (13)Permission denied: [client 36.82.95.104:57256] AH00035: access to /static/images/Twitter-logo-white.png denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/images') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:46:35.927953 2021] [core:error] [pid 52118:tid 139952784340736] (13)Permission denied: [client 36.82.95.104:57255] AH00035: access to /static/images/logo.png denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/images') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:46:35.978512 2021] [core:error] [pid 52118:tid 139953038272256] (13)Permission denied: [client 36.82.95.104:57257] AH00035: access to /static/js/main.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/js') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:46:36.219527 2021] [core:error] [pid 52117:tid 139952910231296] (13)Permission denied: [client 36.82.95.104:57254] AH00035: access to /static/images/logo.png denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/images') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/
[Thu Dec 02 13:51:33.120514 2021] [core:error] [pid 52117:tid 139952868267776] (13)Permission denied: [client 36.82.95.104:57413] AH00035: access to /static/images/logo.png denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos') because search permissions are missing on a component of the path
[Thu Dec 02 13:51:33.210351 2021] [core:error] [pid 52117:tid 139952859875072] (13)Permission denied: [client 36.82.95.104:57414] AH00035: access to /favicon.ico denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul') because search permissions are missing on a component of the path, referer: http://itos.temperantia.my.id/static/images/logo.png
[Thu Dec 02 13:51:34.457971 2021] [core:error] [pid 52117:tid 139952843089664] (13)Permission denied: [client 36.82.95.104:57413] AH00035: access to /static/images/logo.png denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos') because search permissions are missing on a component of the path
[Thu Dec 02 13:51:35.510460 2021] [core:error] [pid 52117:tid 139952834696960] (13)Permission denied: [client 36.82.95.104:57413] AH00035: access to /static/images/logo.png denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos') because search permissions are missing on a component of the path
[Thu Dec 02 13:51:36.041268 2021] [core:error] [pid 52117:tid 139952826304256] (13)Permission denied: [client 36.82.95.104:57413] AH00035: access to /static/images/logo.png denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos') because search permissions are missing on a component of the path
Exception ignored in: <function Local.__del__ at 0x7f49534f6c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Thu Dec 02 13:51:41.941059 2021] [core:error] [pid 59002:tid 140175017563904] (13)Permission denied: [client 36.82.95.104:57425] AH00035: access to /static/js/jquery.min.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos') because search permissions are missing on a component of the path
[Thu Dec 02 13:51:42.503403 2021] [core:error] [pid 59002:tid 140175009171200] (13)Permission denied: [client 36.82.95.104:57425] AH00035: access to /static/js/jquery.min.js denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos') because search permissions are missing on a component of the path
[Thu Dec 02 13:51:43.899516 2021] [core:error] [pid 59002:tid 140175000778496] (13)Permission denied: [client 36.82.95.104:57425] AH00035: access to / denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul') because search permissions are missing on a component of the path
[Thu Dec 02 13:51:45.272082 2021] [core:error] [pid 59002:tid 140174992385792] (13)Permission denied: [client 36.82.95.104:57425] AH00035: access to / denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul') because search permissions are missing on a component of the path
[Thu Dec 02 13:51:45.932526 2021] [core:error] [pid 59002:tid 140174914746112] (13)Permission denied: [client 36.82.95.104:57425] AH00035: access to / denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul') because search permissions are missing on a component of the path
[Thu Dec 02 13:51:46.427361 2021] [core:error] [pid 59002:tid 140174906353408] (13)Permission denied: [client 36.82.95.104:57425] AH00035: access to / denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul') because search permissions are missing on a component of the path
[Thu Dec 02 13:51:47.324732 2021] [core:error] [pid 59002:tid 140174897960704] (13)Permission denied: [client 36.82.95.104:57425] AH00035: access to / denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul') because search permissions are missing on a component of the path
[Thu Dec 02 13:51:48.029609 2021] [core:error] [pid 59002:tid 140174889568000] (13)Permission denied: [client 36.82.95.104:57425] AH00035: access to / denied (filesystem path '/home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul') because search permissions are missing on a component of the path
[Thu Dec 02 13:53:16.131444 2021] [wsgi:error] [pid 59181:tid 140174975600384] [remote 36.82.95.104:57436] /home/temperantia/All_TavernofSoul/TavernofSoul/Items/views.py:17: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Thu Dec 02 13:53:16.131484 2021] [wsgi:error] [pid 59181:tid 140174975600384] [remote 36.82.95.104:57436] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Thu Dec 02 13:53:16.131489 2021] [wsgi:error] [pid 59181:tid 140174975600384] [remote 36.82.95.104:57436]   import numpy as np
Exception ignored in: <function Local.__del__ at 0x7f7d01ce8c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Thu Dec 02 13:54:12.820524 2021] [wsgi:error] [pid 59262:tid 140279975913216] [remote 36.82.95.104:57479] /home/temperantia/All_TavernofSoul/TavernofSoul/Items/views.py:17: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Thu Dec 02 13:54:12.820579 2021] [wsgi:error] [pid 59262:tid 140279975913216] [remote 36.82.95.104:57479] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Thu Dec 02 13:54:12.820583 2021] [wsgi:error] [pid 59262:tid 140279975913216] [remote 36.82.95.104:57479]   import numpy as np
Exception ignored in: <function Local.__del__ at 0x7f9576505c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Thu Dec 02 13:56:54.180208 2021] [wsgi:error] [pid 59453:tid 140447145920256] [remote 36.82.95.104:57551] /home/temperantia/All_TavernofSoul/TavernofSoul/Items/views.py:17: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Thu Dec 02 13:56:54.180262 2021] [wsgi:error] [pid 59453:tid 140447145920256] [remote 36.82.95.104:57551] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Thu Dec 02 13:56:54.180267 2021] [wsgi:error] [pid 59453:tid 140447145920256] [remote 36.82.95.104:57551]   import numpy as np
Exception ignored in: <function Local.__del__ at 0x7fbc626c4c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 03 01:35:15.483348 2021] [wsgi:error] [pid 86710:tid 139816797062912] [remote 112.215.240.185:9888] /home/temperantia/All_TavernofSoul/TavernofSoul/Items/views.py:17: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 01:35:15.484098 2021] [wsgi:error] [pid 86710:tid 139816797062912] [remote 112.215.240.185:9888] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 01:35:15.484110 2021] [wsgi:error] [pid 86710:tid 139816797062912] [remote 112.215.240.185:9888]   import numpy as np
Exception ignored in: <function Local.__del__ at 0x7f2997b2ac10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 03 01:45:42.678739 2021] [wsgi:error] [pid 88398:tid 140126625511168] [remote 112.215.240.185:10023] /home/temperantia/All_TavernofSoul/TavernofSoul/Items/views.py:17: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 01:45:42.679880 2021] [wsgi:error] [pid 88398:tid 140126625511168] [remote 112.215.240.185:10023] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 01:45:42.679894 2021] [wsgi:error] [pid 88398:tid 140126625511168] [remote 112.215.240.185:10023]   import numpy as np
Exception ignored in: <function Local.__del__ at 0x7f71bdea8c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 03 02:14:04.592401 2021] [wsgi:error] [pid 91619:tid 140412516103936] [remote 112.215.240.185:10199] /home/temperantia/All_TavernofSoul/TavernofSoul/Items/views.py:17: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 02:14:04.592812 2021] [wsgi:error] [pid 91619:tid 140412516103936] [remote 112.215.240.185:10199] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 02:14:04.592820 2021] [wsgi:error] [pid 91619:tid 140412516103936] [remote 112.215.240.185:10199]   import numpy as np
Exception ignored in: <function Local.__del__ at 0x7fb44e52bc10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 03 02:46:34.291858 2021] [wsgi:error] [pid 93254:tid 140703257765632] [remote 112.215.240.185:11062] /home/temperantia/All_TavernofSoul/TavernofSoul/Items/views.py:17: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 02:46:34.291914 2021] [wsgi:error] [pid 93254:tid 140703257765632] [remote 112.215.240.185:11062] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 02:46:34.291918 2021] [wsgi:error] [pid 93254:tid 140703257765632] [remote 112.215.240.185:11062]   import numpy as np
Exception ignored in: <function Local.__del__ at 0x7ff7fbdf3c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 03 02:57:30.722867 2021] [wsgi:error] [pid 93814:tid 140593961182976] [remote 216.244.66.239:41892] /home/temperantia/All_TavernofSoul/TavernofSoul/Items/views.py:17: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 02:57:30.722931 2021] [wsgi:error] [pid 93814:tid 140593961182976] [remote 216.244.66.239:41892] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 02:57:30.722937 2021] [wsgi:error] [pid 93814:tid 140593961182976] [remote 216.244.66.239:41892]   import numpy as np
Exception ignored in: <function Local.__del__ at 0x7fde8d4aec10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 03 03:01:11.452569 2021] [wsgi:error] [pid 95713:tid 140593961182976] [remote 82.193.104.168:13916] /home/temperantia/All_TavernofSoul/TavernofSoul/Items/views.py:17: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 03:01:11.452625 2021] [wsgi:error] [pid 95713:tid 140593961182976] [remote 82.193.104.168:13916] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 03:01:11.452629 2021] [wsgi:error] [pid 95713:tid 140593961182976] [remote 82.193.104.168:13916]   import numpy as np
Exception ignored in: <function Local.__del__ at 0x7fde8d4a6c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 03 03:03:20.519996 2021] [wsgi:error] [pid 96526:tid 140593961182976] [remote 82.193.104.168:13922] /home/temperantia/All_TavernofSoul/TavernofSoul/Items/views.py:17: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 03:03:20.521303 2021] [wsgi:error] [pid 96526:tid 140593961182976] [remote 82.193.104.168:13922] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 03:03:20.521318 2021] [wsgi:error] [pid 96526:tid 140593961182976] [remote 82.193.104.168:13922]   import numpy as np
Exception ignored in: <function Local.__del__ at 0x7fde8d49cc10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 03 03:03:48.517800 2021] [wsgi:error] [pid 97428:tid 140593961182976] [remote 82.193.104.168:13924] /home/temperantia/All_TavernofSoul/TavernofSoul/Items/views.py:17: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 03:03:48.517841 2021] [wsgi:error] [pid 97428:tid 140593961182976] [remote 82.193.104.168:13924] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 03:03:48.517846 2021] [wsgi:error] [pid 97428:tid 140593961182976] [remote 82.193.104.168:13924]   import numpy as np
Exception ignored in: <function Local.__del__ at 0x7fde8d48ec10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 03 03:04:55.278838 2021] [wsgi:error] [pid 97675:tid 139664786867968] [remote 144.76.40.26:49491] /home/temperantia/All_TavernofSoul/TavernofSoul/Items/views.py:17: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 03:04:55.278899 2021] [wsgi:error] [pid 97675:tid 139664786867968] [remote 144.76.40.26:49491] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 03:04:55.281436 2021] [wsgi:error] [pid 97675:tid 139664786867968] [remote 144.76.40.26:49491]   import numpy as np
Exception ignored in: <function Local.__del__ at 0x7f063c30dc10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Fri Dec 03 03:11:54.675500 2021] [wsgi:error] [pid 98068:tid 139843683251968] [remote 180.245.6.142:64555] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 03:11:54.675559 2021] [wsgi:error] [pid 98068:tid 139843683251968] [remote 180.245.6.142:64555] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 03:11:54.675565 2021] [wsgi:error] [pid 98068:tid 139843683251968] [remote 180.245.6.142:64555]   __import__(dependency)
[Fri Dec 03 04:58:27.790218 2021] [wsgi:error] [pid 98068:tid 139843683251968] [remote 66.249.79.31:63528] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Attributes.models.Attributes'> QuerySet.
[Fri Dec 03 04:58:27.790477 2021] [wsgi:error] [pid 98068:tid 139843683251968] [remote 66.249.79.31:63528]   return paginator.Paginator(self._items(), self.limit)
[Fri Dec 03 04:58:27.964264 2021] [wsgi:error] [pid 98068:tid 139843683251968] [remote 66.249.79.31:63528] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Buffs.models.Buffs'> QuerySet.
[Fri Dec 03 04:58:27.964312 2021] [wsgi:error] [pid 98068:tid 139843683251968] [remote 66.249.79.31:63528]   return paginator.Paginator(self._items(), self.limit)
[Fri Dec 03 04:58:28.268778 2021] [wsgi:error] [pid 98068:tid 139843683251968] [remote 66.249.79.31:63528] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Items.models.Items'> QuerySet.
[Fri Dec 03 04:58:28.268818 2021] [wsgi:error] [pid 98068:tid 139843683251968] [remote 66.249.79.31:63528]   return paginator.Paginator(self._items(), self.limit)
[Fri Dec 03 04:58:30.838507 2021] [wsgi:error] [pid 98068:tid 139843683251968] [remote 66.249.79.31:63528] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Jobs.models.Jobs'> QuerySet.
[Fri Dec 03 04:58:30.838548 2021] [wsgi:error] [pid 98068:tid 139843683251968] [remote 66.249.79.31:63528]   return paginator.Paginator(self._items(), self.limit)
[Fri Dec 03 04:58:30.873579 2021] [wsgi:error] [pid 98068:tid 139843683251968] [remote 66.249.79.31:63528] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Maps.models.Maps'> QuerySet.
[Fri Dec 03 04:58:30.873620 2021] [wsgi:error] [pid 98068:tid 139843683251968] [remote 66.249.79.31:63528]   return paginator.Paginator(self._items(), self.limit)
[Fri Dec 03 04:58:30.940885 2021] [wsgi:error] [pid 98068:tid 139843683251968] [remote 66.249.79.31:63528] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Skills.models.Skills'> QuerySet.
[Fri Dec 03 04:58:30.940939 2021] [wsgi:error] [pid 98068:tid 139843683251968] [remote 66.249.79.31:63528]   return paginator.Paginator(self._items(), self.limit)
[Fri Dec 03 06:48:12.217069 2021] [wsgi:error] [pid 98078:tid 139843581499136] [client 122.60.67.206:62714] Truncated or oversized response headers received from daemon process 'django_itos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_itos.py, referer: https://itos.tavernofsoul.com/
[Fri Dec 03 06:48:15.865381 2021] [wsgi:error] [pid 101751:tid 139843683251968] [remote 122.60.67.206:62716] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 06:48:15.867441 2021] [wsgi:error] [pid 101751:tid 139843683251968] [remote 122.60.67.206:62716] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 06:48:15.867453 2021] [wsgi:error] [pid 101751:tid 139843683251968] [remote 122.60.67.206:62716]   __import__(dependency)
[Fri Dec 03 07:27:23.044974 2021] [wsgi:error] [pid 102806:tid 139843683251968] [remote 49.230.131.171:60328] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 07:27:23.046023 2021] [wsgi:error] [pid 102806:tid 139843683251968] [remote 49.230.131.171:60328] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 07:27:23.046048 2021] [wsgi:error] [pid 102806:tid 139843683251968] [remote 49.230.131.171:60328]   __import__(dependency)
[Fri Dec 03 07:38:27.262786 2021] [wsgi:error] [pid 138281:tid 139843564713728] (2)No such file or directory: [client 185.191.171.2:12532] mod_wsgi (pid=138281): Unable to connect to WSGI daemon process 'django_itos' on '/var/run/apache2/wsgi.98067.3.2.sock' as user with uid=33.
[Fri Dec 03 07:40:28.638214 2021] [wsgi:error] [pid 139179:tid 139843666466560] [remote 211.36.37.150:54293] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Fri Dec 03 07:40:28.639639 2021] [wsgi:error] [pid 139179:tid 139843666466560] [remote 211.36.37.150:54293] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Fri Dec 03 07:40:28.639653 2021] [wsgi:error] [pid 139179:tid 139843666466560] [remote 211.36.37.150:54293]   __import__(dependency)
[Fri Dec 03 14:13:49.446711 2021] [autoindex:error] [pid 139190:tid 139843581499136] [client 93.158.161.74:49850] AH01276: Cannot serve directory /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive
[Sat Dec 04 00:00:05.756552 2021] [wsgi:error] [pid 139191:tid 139843683251968] [client 206.189.33.118:48956] Truncated or oversized response headers received from daemon process 'django_itos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_itos.py
[Sat Dec 04 00:00:08.926419 2021] [wsgi:error] [pid 153897:tid 139843683251968] [remote 40.77.167.9:19392] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sat Dec 04 00:00:08.926478 2021] [wsgi:error] [pid 153897:tid 139843683251968] [remote 40.77.167.9:19392] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sat Dec 04 00:00:08.926485 2021] [wsgi:error] [pid 153897:tid 139843683251968] [remote 40.77.167.9:19392]   __import__(dependency)
[Sat Dec 04 03:19:20.258276 2021] [wsgi:error] [pid 153897:tid 139843683251968] [remote 71.6.158.166:32824] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Attributes.models.Attributes'> QuerySet.
[Sat Dec 04 03:19:20.258795 2021] [wsgi:error] [pid 153897:tid 139843683251968] [remote 71.6.158.166:32824]   return paginator.Paginator(self._items(), self.limit)
[Sat Dec 04 03:19:20.535527 2021] [wsgi:error] [pid 153897:tid 139843683251968] [remote 71.6.158.166:32824] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Buffs.models.Buffs'> QuerySet.
[Sat Dec 04 03:19:20.535572 2021] [wsgi:error] [pid 153897:tid 139843683251968] [remote 71.6.158.166:32824]   return paginator.Paginator(self._items(), self.limit)
[Sat Dec 04 03:19:21.933643 2021] [wsgi:error] [pid 153897:tid 139843683251968] [remote 71.6.158.166:32824] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Items.models.Items'> QuerySet.
[Sat Dec 04 03:19:21.933686 2021] [wsgi:error] [pid 153897:tid 139843683251968] [remote 71.6.158.166:32824]   return paginator.Paginator(self._items(), self.limit)
[Sat Dec 04 03:19:24.873628 2021] [wsgi:error] [pid 153897:tid 139843683251968] [remote 71.6.158.166:32824] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Jobs.models.Jobs'> QuerySet.
[Sat Dec 04 03:19:24.873671 2021] [wsgi:error] [pid 153897:tid 139843683251968] [remote 71.6.158.166:32824]   return paginator.Paginator(self._items(), self.limit)
[Sat Dec 04 03:19:24.923866 2021] [wsgi:error] [pid 153897:tid 139843683251968] [remote 71.6.158.166:32824] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Maps.models.Maps'> QuerySet.
[Sat Dec 04 03:19:24.923902 2021] [wsgi:error] [pid 153897:tid 139843683251968] [remote 71.6.158.166:32824]   return paginator.Paginator(self._items(), self.limit)
[Sat Dec 04 03:19:25.004992 2021] [wsgi:error] [pid 153897:tid 139843683251968] [remote 71.6.158.166:32824] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Skills.models.Skills'> QuerySet.
[Sat Dec 04 03:19:25.005060 2021] [wsgi:error] [pid 153897:tid 139843683251968] [remote 71.6.158.166:32824]   return paginator.Paginator(self._items(), self.limit)
[Sat Dec 04 04:05:28.046273 2021] [wsgi:error] [pid 153935:tid 139843691644672] (70007)The timeout specified has expired: [client 45.175.12.47:58897] mod_wsgi (pid=153935): Failed to proxy response to client.
[Sat Dec 04 04:30:27.599790 2021] [autoindex:error] [pid 153935:tid 139843589891840] [client 93.158.161.74:56774] AH01276: Cannot serve directory /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/admin/js/vendor/select2/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive
[Sat Dec 04 16:34:46.990201 2021] [autoindex:error] [pid 153935:tid 139843480786688] [client 93.158.161.74:62056] AH01276: Cannot serve directory /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/admin/js/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive
[Sat Dec 04 21:30:33.572146 2021] [log_config:warn] [pid 153908:tid 139843505964800] (28)No space left on device: [client 68.186.206.10:59491] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSoul/itos/access.log, referer: https://itos.tavernofsoul.com/
[Sat Dec 04 21:30:34.015688 2021] [log_config:warn] [pid 153935:tid 139843531142912] (28)No space left on device: [client 68.186.206.10:59490] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSoul/itos/access.log, referer: https://itos.tavernofsoul.com/
[Sat Dec 04 21:30:34.115662 2021] [log_config:warn] [pid 153935:tid 139843455608576] (28)No space left on device: [client 68.186.206.10:59493] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSoul/itos/access.log, referer: https://itos.tavernofsoul.com/
[Sat Dec 04 21:30:34.130921 2021] [log_config:warn] [pid 153908:tid 139843522750208] (28)No space left on device: [client 68.186.206.10:59491] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSoul/itos/access.log, referer: https://itos.tavernofsoul.com/
[Sat Dec 04 21:30:34.303029 2021] [log_config:warn] [pid 153935:tid 139843497572096] (28)No space left on device: [client 68.186.206.10:59490] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSoul/itos/access.log, referer: https://itos.tavernofsoul.com/
[Sat Dec 04 21:30:34.398981 2021] [log_config:warn] [pid 153935:tid 139843539535616] (28)No space left on device: [client 68.186.206.10:59493] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSoul/itos/access.log, referer: https://itos.tavernofsoul.com/
[Sat Dec 04 21:30:34.410102 2021] [log_config:warn] [pid 153908:tid 139843447215872] (28)No space left on device: [client 68.186.206.10:59491] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSoul/itos/access.log, referer: https://itos.tavernofsoul.com/
[Sat Dec 04 21:30:39.286033 2021] [log_config:warn] [pid 153935:tid 139843581499136] (28)No space left on device: [client 68.186.206.10:59493] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSoul/itos/access.log, referer: https://itos.tavernofsoul.com/
[Sat Dec 04 21:30:39.635830 2021] [log_config:warn] [pid 153935:tid 139843464001280] (28)No space left on device: [client 68.186.206.10:59493] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSoul/itos/access.log, referer: https://itos.tavernofsoul.com/?q=written
[Sat Dec 04 21:30:39.636081 2021] [log_config:warn] [pid 153935:tid 139843547928320] (28)No space left on device: [client 68.186.206.10:59495] AH00646: Error writing to /home/temperantia/All_TavernofSoul/TavernofSoul/itos/access.lo[Sun Dec 05 00:29:51.776234 2021] [wsgi:error] [pid 153908:tid 139843480786688] [client 193.160.245.197:64708] Truncated or oversized response headers received from daemon process 'django_itos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_itos.py, referer: https://itos.tavernofsoul.com/
[Sun Dec 05 00:29:51.767392 2021] [wsgi:error] [pid 153908:tid 139843564713728] [client 193.160.245.197:65048] Truncated or oversized response headers received from daemon process 'django_itos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_itos.py
[Sun Dec 05 00:29:51.774475 2021] [wsgi:error] [pid 153935:tid 139843472393984] [client 193.160.245.197:64710] Truncated or oversized response headers received from daemon process 'django_itos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_itos.py, referer: https://itos.tavernofsoul.com/
[Sun Dec 05 00:29:51.782723 2021] [wsgi:error] [pid 153935:tid 139843489179392] [client 193.160.245.197:63324] Truncated or oversized response headers received from daemon process 'django_itos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_itos.py, referer: https://itos.tavernofsoul.com/
[Sun Dec 05 00:29:51.783211 2021] [wsgi:error] [pid 153935:tid 139843691644672] [client 193.160.245.197:62690] Truncated or oversized response headers received from daemon process 'django_itos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_itos.py, referer: https://itos.tavernofsoul.com/
[Sun Dec 05 00:29:51.783249 2021] [wsgi:error] [pid 153908:tid 139843505964800] [client 193.160.245.197:62688] Truncated or oversized response headers received from daemon process 'django_itos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_itos.py, referer: https://itos.tavernofsoul.com/
[Sun Dec 05 00:29:57.132582 2021] [wsgi:error] [pid 171526:tid 139843683251968] [remote 193.160.245.197:2812] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sun Dec 05 00:29:57.140904 2021] [wsgi:error] [pid 171526:tid 139843683251968] [remote 193.160.245.197:2812] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sun Dec 05 00:29:57.140929 2021] [wsgi:error] [pid 171526:tid 139843683251968] [remote 193.160.245.197:2812]   __import__(dependency)
[Sun Dec 05 00:31:22.670927 2021] [wsgi:error] [pid 171624:tid 139843574146816] [remote 125.164.230.14:61614] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sun Dec 05 00:31:22.675011 2021] [wsgi:error] [pid 171624:tid 139843574146816] [remote 125.164.230.14:61614] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sun Dec 05 00:31:22.675024 2021] [wsgi:error] [pid 171624:tid 139843574146816] [remote 125.164.230.14:61614]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f2fdd3e2c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Sun Dec 05 00:42:57.512363 2021] [wsgi:error] [pid 172272:tid 139843683251968] [remote 223.206.66.210:55696] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sun Dec 05 00:42:57.512410 2021] [wsgi:error] [pid 172272:tid 139843683251968] [remote 223.206.66.210:55696] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sun Dec 05 00:42:57.512414 2021] [wsgi:error] [pid 172272:tid 139843683251968] [remote 223.206.66.210:55696]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f2fdd3e2c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Sun Dec 05 00:44:10.194795 2021] [wsgi:error] [pid 172611:tid 139843683251968] [remote 125.164.230.14:51245] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sun Dec 05 00:44:10.194839 2021] [wsgi:error] [pid 172611:tid 139843683251968] [remote 125.164.230.14:51245] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sun Dec 05 00:44:10.194844 2021] [wsgi:error] [pid 172611:tid 139843683251968] [remote 125.164.230.14:51245]   __import__(dependency)
[Sun Dec 05 02:45:41.374214 2021] [wsgi:error] [pid 172611:tid 139843683251968] [remote 180.253.161.152:17952] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Attributes.models.Attributes'> QuerySet.
[Sun Dec 05 02:45:41.375434 2021] [wsgi:error] [pid 172611:tid 139843683251968] [remote 180.253.161.152:17952]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 05 02:45:41.872116 2021] [wsgi:error] [pid 172611:tid 139843683251968] [remote 180.253.161.152:17952] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Buffs.models.Buffs'> QuerySet.
[Sun Dec 05 02:45:41.872154 2021] [wsgi:error] [pid 172611:tid 139843683251968] [remote 180.253.161.152:17952]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 05 02:45:42.783571 2021] [wsgi:error] [pid 172611:tid 139843683251968] [remote 180.253.161.152:17952] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Items.models.Items'> QuerySet.
[Sun Dec 05 02:45:42.783612 2021] [wsgi:error] [pid 172611:tid 139843683251968] [remote 180.253.161.152:17952]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 05 02:45:49.152098 2021] [wsgi:error] [pid 172611:tid 139843683251968] [remote 180.253.161.152:17952] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Jobs.models.Jobs'> QuerySet.
[Sun Dec 05 02:45:49.152147 2021] [wsgi:error] [pid 172611:tid 139843683251968] [remote 180.253.161.152:17952]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 05 02:45:49.220767 2021] [wsgi:error] [pid 172611:tid 139843683251968] [remote 180.253.161.152:17952] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Maps.models.Maps'> QuerySet.
[Sun Dec 05 02:45:49.220806 2021] [wsgi:error] [pid 172611:tid 139843683251968] [remote 180.253.161.152:17952]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 05 02:45:49.372597 2021] [wsgi:error] [pid 172611:tid 139843683251968] [remote 180.253.161.152:17952] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Skills.models.Skills'> QuerySet.
[Sun Dec 05 02:45:49.372635 2021] [wsgi:error] [pid 172611:tid 139843683251968] [remote 180.253.161.152:17952]   return paginator.Paginator(self._items(), self.limit)
Exception ignored in: <function Local.__del__ at 0x7f2fdd3e3c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Sun Dec 05 03:08:30.312872 2021] [wsgi:error] [pid 175224:tid 139843683251968] [remote 180.253.161.152:6496] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sun Dec 05 03:08:30.313096 2021] [wsgi:error] [pid 175224:tid 139843683251968] [remote 180.253.161.152:6496] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sun Dec 05 03:08:30.313104 2021] [wsgi:error] [pid 175224:tid 139843683251968] [remote 180.253.161.152:6496]   __import__(dependency)
[Sun Dec 05 03:08:30.631914 2021] [wsgi:error] [pid 175224:tid 139843683251968] [remote 180.253.161.152:6496] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Attributes.models.Attributes'> QuerySet.
[Sun Dec 05 03:08:30.631945 2021] [wsgi:error] [pid 175224:tid 139843683251968] [remote 180.253.161.152:6496]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 05 03:08:30.822503 2021] [wsgi:error] [pid 175224:tid 139843683251968] [remote 180.253.161.152:6496] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Buffs.models.Buffs'> QuerySet.
[Sun Dec 05 03:08:30.822551 2021] [wsgi:error] [pid 175224:tid 139843683251968] [remote 180.253.161.152:6496]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 05 03:08:31.119371 2021] [wsgi:error] [pid 175224:tid 139843683251968] [remote 180.253.161.152:6496] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Items.models.Items'> QuerySet.
[Sun Dec 05 03:08:31.119413 2021] [wsgi:error] [pid 175224:tid 139843683251968] [remote 180.253.161.152:6496]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 05 03:08:33.665711 2021] [wsgi:error] [pid 175224:tid 139843683251968] [remote 180.253.161.152:6496] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Jobs.models.Jobs'> QuerySet.
[Sun Dec 05 03:08:33.665783 2021] [wsgi:error] [pid 175224:tid 139843683251968] [remote 180.253.161.152:6496]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 05 03:08:33.702939 2021] [wsgi:error] [pid 175224:tid 139843683251968] [remote 180.253.161.152:6496] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Maps.models.Maps'> QuerySet.
[Sun Dec 05 03:08:33.702978 2021] [wsgi:error] [pid 175224:tid 139843683251968] [remote 180.253.161.152:6496]   return paginator.Paginator(self._items(), self.limit)
[Sun Dec 05 03:08:33.779930 2021] [wsgi:error] [pid 175224:tid 139843683251968] [remote 180.253.161.152:6496] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/contrib/sitemaps/__init__.py:115: UnorderedObjectListWarning: Pagination may yield inconsistent results with an unordered object_list: <class 'Skills.models.Skills'> QuerySet.
[Sun Dec 05 03:08:33.779974 2021] [wsgi:error] [pid 175224:tid 139843683251968] [remote 180.253.161.152:6496]   return paginator.Paginator(self._items(), self.limit)
Exception ignored in: <function Local.__del__ at 0x7f2fdd3e2c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Sun Dec 05 03:09:09.029939 2021] [wsgi:error] [pid 175547:tid 139843683251968] [remote 185.191.171.39:62134] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sun Dec 05 03:09:09.029982 2021] [wsgi:error] [pid 175547:tid 139843683251968] [remote 185.191.171.39:62134] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sun Dec 05 03:09:09.029986 2021] [wsgi:error] [pid 175547:tid 139843683251968] [remote 185.191.171.39:62134]   __import__(dependency)
[Sun Dec 05 07:09:05.189081 2021] [ssl:error] [pid 175559:tid 139843598284544] [client 34.230.52.157:47752] AH02042: rejecting client initiated renegotiation
[Sun Dec 05 15:05:04.452024 2021] [autoindex:error] [pid 175558:tid 139843598284544] [client 93.158.161.74:60646] AH01276: Cannot serve directory /home/temperantia/All_TavernofSoul/TavernofSoul/staticfiles_itos/admin/js/vendor/xregexp/: No matching DirectoryIndex (index.html,index.cgi,index.pl,index.php,index.xhtml,index.htm) found, and server-generated directory index forbidden by Options directive
Exception ignored in: <function Local.__del__ at 0x7f2fdd3e3c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Sun Dec 05 15:11:51.353608 2021] [wsgi:error] [pid 185031:tid 139843683251968] [remote 125.164.1.83:52903] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sun Dec 05 15:11:51.353651 2021] [wsgi:error] [pid 185031:tid 139843683251968] [remote 125.164.1.83:52903] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sun Dec 05 15:11:51.353667 2021] [wsgi:error] [pid 185031:tid 139843683251968] [remote 125.164.1.83:52903]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f2fdd3e2c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f2fdd3e2c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Sun Dec 05 15:12:26.035241 2021] [wsgi:error] [pid 185334:tid 139843683251968] [remote 125.164.1.83:52920] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sun Dec 05 15:12:26.035282 2021] [wsgi:error] [pid 185334:tid 139843683251968] [remote 125.164.1.83:52920] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sun Dec 05 15:12:26.035286 2021] [wsgi:error] [pid 185334:tid 139843683251968] [remote 125.164.1.83:52920]   __import__(dependency)
[Sun Dec 05 15:12:26.326045 2021] [wsgi:error] [pid 185334:tid 139843683251968] [remote 125.164.1.83:52920] Internal Server Error: /planner/
[Sun Dec 05 15:12:26.326108 2021] [wsgi:error] [pid 185334:tid 139843683251968] [remote 125.164.1.83:52920] Traceback (most recent call last):
[Sun Dec 05 15:12:26.326115 2021] [wsgi:error] [pid 185334:tid 139843683251968] [remote 125.164.1.83:52920]   File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/core/handlers/exception.py", line 47, in inner
[Sun Dec 05 15:12:26.326119 2021] [wsgi:error] [pid 185334:tid 139843683251968] [remote 125.164.1.83:52920]     response = get_response(request)
[Sun Dec 05 15:12:26.326122 2021] [wsgi:error] [pid 185334:tid 139843683251968] [remote 125.164.1.83:52920]   File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/django/core/handlers/base.py", line 181, in _get_response
[Sun Dec 05 15:12:26.326126 2021] [wsgi:error] [pid 185334:tid 139843683251968] [remote 125.164.1.83:52920]     response = wrapped_callback(request, *callback_args, **callback_kwargs)
[Sun Dec 05 15:12:26.326130 2021] [wsgi:error] [pid 185334:tid 139843683251968] [remote 125.164.1.83:52920]   File "/home/temperantia/All_TavernofSoul/TavernofSoul/Planner/views.py", line 101, in index
[Sun Dec 05 15:12:26.326133 2021] [wsgi:error] [pid 185334:tid 139843683251968] [remote 125.164.1.83:52920]     l['cooldown_lv']        = l.cooldown_lv
[Sun Dec 05 15:12:26.326137 2021] [wsgi:error] [pid 185334:tid 139843683251968] [remote 125.164.1.83:52920] TypeError: 'Skills' object does not support item assignment
Exception ignored in: <function Local.__del__ at 0x7f2fdd3e2c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f2fdd3e2c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Sun Dec 05 15:12:48.698224 2021] [wsgi:error] [pid 185630:tid 139843683251968] [remote 187.120.30.221:57232] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sun Dec 05 15:12:48.698285 2021] [wsgi:error] [pid 185630:tid 139843683251968] [remote 187.120.30.221:57232] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sun Dec 05 15:12:48.698289 2021] [wsgi:error] [pid 185630:tid 139843683251968] [remote 187.120.30.221:57232]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f2fdd3e3c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
Exception ignored in: <function Local.__del__ at 0x7f2fdd3e3c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Sun Dec 05 15:13:12.676082 2021] [wsgi:error] [pid 185846:tid 139843430430464] (2)No such file or directory: [client 187.120.30.221:57227] mod_wsgi (pid=185846): Unable to connect to WSGI daemon process 'django_itos' on '/var/run/apache2/wsgi.98067.15.2.sock' as user with uid=33., referer: https://itos.tavernofsoul.com/items/
[Sun Dec 05 15:13:13.150266 2021] [wsgi:error] [pid 185960:tid 139843683251968] [remote 125.164.1.83:52940] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sun Dec 05 15:13:13.150305 2021] [wsgi:error] [pid 185960:tid 139843683251968] [remote 125.164.1.83:52940] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sun Dec 05 15:13:13.150309 2021] [wsgi:error] [pid 185960:tid 139843683251968] [remote 125.164.1.83:52940]   __import__(dependency)
[Sun Dec 05 15:13:14.599755 2021] [wsgi:error] [pid 185846:tid 139843447215872] (2)No such file or directory: [client 187.120.30.221:57242] mod_wsgi (pid=185846): Unable to connect to WSGI daemon process 'django_itos' on '/var/run/apache2/wsgi.98067.15.2.sock' as user with uid=33., referer: https://itos.tavernofsoul.com/items/
Exception ignored in: <function Local.__del__ at 0x7f2fdd3e2c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Sun Dec 05 15:28:27.798000 2021] [wsgi:error] [pid 186550:tid 139843683251968] [remote 125.164.1.83:50474] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Sun Dec 05 15:28:27.798041 2021] [wsgi:error] [pid 186550:tid 139843683251968] [remote 125.164.1.83:50474] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Sun Dec 05 15:28:27.798046 2021] [wsgi:error] [pid 186550:tid 139843683251968] [remote 125.164.1.83:50474]   __import__(dependency)
[Sun Dec 05 21:07:58.915247 2021] [core:error] [pid 186765:tid 139843674859264] [client 45.155.205.233:50786] AH00126: Invalid URI in request POST /cgi-bin/.%2e/.%2e/.%2e/.%2e/bin/sh HTTP/1.1
[Sun Dec 05 23:12:43.948956 2021] [wsgi:error] [pid 186766:tid 139843422037760] [client 138.68.249.116:56790] Invalid Content-Length header value of '18446744073709551615' was supplied.: /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_itos.py
[Mon Dec 06 00:00:06.184669 2021] [wsgi:error] [pid 186765:tid 139843430430464] [client 206.189.33.118:54392] Truncated or oversized response headers received from daemon process 'django_itos': /home/temperantia/All_TavernofSoul/TavernofSoul/TavernofSoul/wsgi_itos.py
[Mon Dec 06 00:00:46.126224 2021] [wsgi:error] [pid 191903:tid 139843683251968] [remote 40.77.167.9:18752] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Mon Dec 06 00:00:46.126268 2021] [wsgi:error] [pid 191903:tid 139843683251968] [remote 40.77.167.9:18752] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Mon Dec 06 00:00:46.126273 2021] [wsgi:error] [pid 191903:tid 139843683251968] [remote 40.77.167.9:18752]   __import__(dependency)
Exception ignored in: <function Local.__del__ at 0x7f2fdd3e3c10>
Traceback (most recent call last):
  File "/home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/asgiref/local.py", line 96, in __del__
NameError: name 'TypeError' is not defined
[Mon Dec 06 00:53:16.973027 2021] [wsgi:error] [pid 831:tid 140024507725568] [remote 112.215.154.250:7518] /home/temperantia/All_TavernofSoul/TavernofSoul/itos/3.8/lib/python3.8/site-packages/pandas/__init__.py:11: UserWarning: NumPy was imported from a Python sub-interpreter but NumPy does not properly support sub-interpreters. This will likely work for most users but might cause hard to track down issues or subtle bugs. A common user of the rare sub-interpreter feature is wsgi which also allows single-interpreter mode.
[Mon Dec 06 00:53:16.973819 2021] [wsgi:error] [pid 831:tid 140024507725568] [remote 112.215.154.250:7518] Improvements in the case of bugs are welcome, but is not on the NumPy roadmap, and full support may require significant effort to achieve.
[Mon Dec 06 00:53:16.973839 2021] [wsgi:error] [pid 831:tid 140024507725568] [remote 112.215.154.250:7518]   __import__(dependency)
[Mon Dec 06 01:16:20.477309 2021] [wsgi:error] [pid 845:tid 140024288851712] (70007)The timeout specified has expired: [client 190.237.157.44:14382] mod_wsgi (pid=845): Failed to proxy response to client., referer: https://itos.tavernofsoul.com/
[Mon Dec 06 01:16:21.400734 2021] [wsgi:error] [pid 845:tid 140024314029824] (70007)The timeout specified has expired: [client 190.237.157.44:14339] mod_wsgi (pid=845): Failed to proxy response to client., referer: https://itos.tavernofsoul.com/
